### ISSUE TITLE
Error: express deprecated req.host: Use req.hostname instead node_modules/utils-merge/index.js:19:17

### ISSUE THREAD

**Issue by camdagr8** [jaredhanson/utils-merge#5] opened 2017-10-26 01:13 UTC
Getting this error on... 

Node: 8.1.4
Express 4.16.2

**Comment by jaredhanson** [comment] 2017-10-26 14:38
What does this have to do with this module?

**Comment by camdagr8** [comment] 2017-10-26 15:30
It uses a deprecated property.

**Comment by jaredhanson** [comment] 2017-10-26 15:33
This module does not depend on express, nor access any particular property (including req.host).  This module just merges properties from the objects that are passed to the `merge` function.

Closing.  If you can isolate the error your are seeing as being caused by this module, please reopen.

**Closed by jaredhanson** 2017-10-26 15:33 UTC
